// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package eqfield

import (
	"fmt"
)

func (r *Request) Validate() error {
	// CancelOrderId: omitempty,eqfield=OrderId
	if r.CancelOrderId != nil {
		if r.CancelOrderId != nil {
			if *r.CancelOrderId != r.OrderId {
				return fmt.Errorf("field CancelOrderId must equal field OrderId")
			}
		} else {
			return fmt.Errorf("field CancelOrderId must equal field OrderId (pointer is nil)")
		}
	}
	// OrderId: required
	if r.OrderId == "" {
		return fmt.Errorf("field OrderId is required")
	}
	return nil
}

func (u *UserPasswordConfirm) Validate() error {
	// Password: required,min=8
	if u.Password == "" {
		return fmt.Errorf("field Password is required")
	}
	if len(u.Password) < 8 {
		return fmt.Errorf("field Password must be at least 8 characters")
	}
	// ConfirmPassword: required,eqfield=Password
	if u.ConfirmPassword == "" {
		return fmt.Errorf("field ConfirmPassword is required")
	}
	if u.ConfirmPassword != u.Password {
		return fmt.Errorf("field ConfirmPassword must equal field Password")
	}
	return nil
}

func (m *MixedPointers) Validate() error {
	// Value1: omitempty,eqfield=Value2
	if m.Value1 != nil {
		if m.Value1 != nil {
			if *m.Value1 != m.Value2 {
				return fmt.Errorf("field Value1 must equal field Value2")
			}
		} else {
			return fmt.Errorf("field Value1 must equal field Value2 (pointer is nil)")
		}
	}
	// Value2: required
	if m.Value2 == 0 {
		return fmt.Errorf("field Value2 is required")
	}
	return nil
}

func (b *BothPointers) Validate() error {
	// Field1: omitempty,eqfield=Field2
	if b.Field1 != nil {
		if b.Field1 != nil && b.Field2 != nil {
			if *b.Field1 != *b.Field2 {
				return fmt.Errorf("field Field1 must equal field Field2")
			}
		} else if (b.Field1 == nil) != (b.Field2 == nil) {
			return fmt.Errorf("field Field1 must equal field Field2")
		}
	}
	return nil
}
