// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package dive_primitives

import (
	"fmt"
	"regexp"
)

var pkg_emailRegexp_952c0aba = regexp.MustCompile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")

func (e *EmailList) Validate() error {
	// Emails: required,dive,email
	if e.Emails == nil || len(e.Emails) == 0 {
		return fmt.Errorf("field Emails is required")
	}
	for i, elem := range e.Emails {
		if !pkg_emailRegexp_952c0aba.MatchString(elem) {
			return fmt.Errorf("field Emails[%d] must be a valid email address", i)
		}
	}
	return nil
}

func (n *NumberList) Validate() error {
	// Numbers: omitempty,dive,min=1,max=100
	if n.Numbers != nil && len(n.Numbers) > 0 {
		for i, elem := range n.Numbers {
			if elem < 1 {
				return fmt.Errorf("field Numbers[%d] must be at least 1", i)
			}
			if elem > 100 {
				return fmt.Errorf("field Numbers[%d] must be at most 100", i)
			}
		}
	}
	return nil
}
