// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package main

import (
	"fmt"
)

func (f *FixedPenalty) Validate() error {
	// Amount: required,gt=0
	if f.Amount == 0 {
		return fmt.Errorf("field Amount is required")
	}
	if f.Amount <= 0 {
		return fmt.Errorf("field Amount must be greater than 0")
	}
	// Currency: required
	if f.Currency == "" {
		return fmt.Errorf("field Currency is required")
	}
	return nil
}

func (p *PercentagePenalty) Validate() error {
	// Percentage: required,gt=0,lte=100
	if p.Percentage == 0 {
		return fmt.Errorf("field Percentage is required")
	}
	if p.Percentage <= 0 {
		return fmt.Errorf("field Percentage must be greater than 0")
	}
	if p.Percentage > 100 {
		return fmt.Errorf("field Percentage must be at most 100")
	}
	return nil
}

func (p *Penalty) Validate() error {
	// FixedPenalty: required_without=PercentagePenalty
	if p.PercentagePenalty == nil && p.FixedPenalty == nil {
		return fmt.Errorf("field FixedPenalty is required when PercentagePenalty is not provided")
	}
	// PercentagePenalty: required_without=FixedPenalty
	if p.FixedPenalty == nil && p.PercentagePenalty == nil {
		return fmt.Errorf("field PercentagePenalty is required when FixedPenalty is not provided")
	}
	// Reason: required
	if p.Reason == "" {
		return fmt.Errorf("field Reason is required")
	}
	return nil
}
