// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package uuid

import (
	"fmt"
	"regexp"
)

var pkg_uuidRegexp_5d285f8c = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")

func (r *Resource) Validate() error {
	// ID: required,uuid
	if r.ID == "" {
		return fmt.Errorf("field ID is required")
	}
	if !pkg_uuidRegexp_5d285f8c.MatchString(r.ID) {
		return fmt.Errorf("field ID must be a valid UUID")
	}
	// OwnerID: uuid
	if !pkg_uuidRegexp_5d285f8c.MatchString(r.OwnerID) {
		return fmt.Errorf("field OwnerID must be a valid UUID")
	}
	// OptionalID: omitempty,uuid
	if r.OptionalID != nil {
		if !pkg_uuidRegexp_5d285f8c.MatchString(*r.OptionalID) {
			return fmt.Errorf("field OptionalID must be a valid UUID")
		}
	}
	// Name: required
	if r.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	return nil
}

func (m *MultipleUUIDs) Validate() error {
	// UserID: required,uuid
	if m.UserID == "" {
		return fmt.Errorf("field UserID is required")
	}
	if !pkg_uuidRegexp_5d285f8c.MatchString(m.UserID) {
		return fmt.Errorf("field UserID must be a valid UUID")
	}
	// SessionID: required,uuid
	if m.SessionID == "" {
		return fmt.Errorf("field SessionID is required")
	}
	if !pkg_uuidRegexp_5d285f8c.MatchString(m.SessionID) {
		return fmt.Errorf("field SessionID must be a valid UUID")
	}
	// RequestID: uuid
	if !pkg_uuidRegexp_5d285f8c.MatchString(m.RequestID) {
		return fmt.Errorf("field RequestID must be a valid UUID")
	}
	// TraceID: uuid
	if !pkg_uuidRegexp_5d285f8c.MatchString(m.TraceID) {
		return fmt.Errorf("field TraceID must be a valid UUID")
	}
	return nil
}
