// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package unique

import (
	"fmt"
)

func (u *UniqueValidation) Validate() error {
	// Users: required,min=1,unique=Email
	if u.Users == nil || len(u.Users) == 0 {
		return fmt.Errorf("field Users is required")
	}
	if len(u.Users) < 1 {
		return fmt.Errorf("field Users must have at least 1 elements")
	}
	seenUsersEmail := make(map[string]bool, len(u.Users))
	for i, item := range u.Users {
		if seenUsersEmail[item.Email] {
			return fmt.Errorf("field Users has duplicate Email at index %d", i)
		}
		seenUsersEmail[item.Email] = true
	}
	// Products: unique=SKU
	seenProductsSKU := make(map[string]bool, len(u.Products))
	for i, item := range u.Products {
		if item == nil {
			continue
		}
		if seenProductsSKU[item.SKU] {
			return fmt.Errorf("field Products has duplicate SKU at index %d", i)
		}
		seenProductsSKU[item.SKU] = true
	}
	// Tags: unique
	seenTags := make(map[string]bool, len(u.Tags))
	for i, item := range u.Tags {
		if seenTags[item] {
			return fmt.Errorf("field Tags has duplicate value at index %d", i)
		}
		seenTags[item] = true
	}
	// CategoryIDs: min=1,unique
	if len(u.CategoryIDs) < 1 {
		return fmt.Errorf("field CategoryIDs must have at least 1 elements")
	}
	seenCategoryIDs := make(map[string]bool, len(u.CategoryIDs))
	for i, item := range u.CategoryIDs {
		key := fmt.Sprintf("%v", item)
		if seenCategoryIDs[key] {
			return fmt.Errorf("field CategoryIDs has duplicate value at index %d", i)
		}
		seenCategoryIDs[key] = true
	}
	return nil
}
