// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package api

import (
	"fmt"
)

func (e *ErrorRs) Validate() error {
	// Errors: required,dive
	if e.Errors == nil || len(e.Errors) == 0 {
		return fmt.Errorf("field Errors is required")
	}
	for i := range e.Errors {
		if err := e.Errors[i].Validate(); err != nil {
			return fmt.Errorf("field Errors[%d] validation failed: %w", i, err)
		}
	}
	return nil
}
