// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package simple

import (
	"fmt"
)

func (b *BasicTypes) Validate() error {
	// Name: required,min=3,max=50
	if b.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	if len(b.Name) < 3 {
		return fmt.Errorf("field Name must be at least 3 characters")
	}
	if len(b.Name) > 50 {
		return fmt.Errorf("field Name must be at most 50 characters")
	}
	// Age: gte=0,lte=150
	if b.Age < 0 {
		return fmt.Errorf("field Age must be at least 0")
	}
	if b.Age > 150 {
		return fmt.Errorf("field Age must be at most 150")
	}
	// Email: required
	if b.Email == "" {
		return fmt.Errorf("field Email is required")
	}
	// Score: gt=0,lt=100
	if b.Score <= 0 {
		return fmt.Errorf("field Score must be greater than 0")
	}
	if b.Score >= 100 {
		return fmt.Errorf("field Score must be less than 100")
	}
	return nil
}

func (m *MinMaxValidation) Validate() error {
	// Username: min=3,max=20
	if len(m.Username) < 3 {
		return fmt.Errorf("field Username must be at least 3 characters")
	}
	if len(m.Username) > 20 {
		return fmt.Errorf("field Username must be at most 20 characters")
	}
	// Count: min=1,max=1000
	if m.Count < 1 {
		return fmt.Errorf("field Count must be at least 1")
	}
	if m.Count > 1000 {
		return fmt.Errorf("field Count must be at most 1000")
	}
	// Rating: min=1,max=5
	if m.Rating < 1 {
		return fmt.Errorf("field Rating must be at least 1")
	}
	if m.Rating > 5 {
		return fmt.Errorf("field Rating must be at most 5")
	}
	return nil
}

func (r *RequiredOnly) Validate() error {
	// ID: required
	if r.ID == "" {
		return fmt.Errorf("field ID is required")
	}
	// Name: required
	if r.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	return nil
}
