// Code generated by validgen. DO NOT EDIT.

package slices

import (
	"fmt"
)

func (s *SliceValidation) Validate() error {
	// Tags: required,min=1,max=10
	if s.Tags == nil || len(s.Tags) == 0 {
		return fmt.Errorf("field Tags is required")
	}
	if len(s.Tags) < 1 {
		return fmt.Errorf("field Tags must have at least 1 elements")
	}
	if len(s.Tags) > 10 {
		return fmt.Errorf("field Tags must have at most 10 elements")
	}
	// Categories: omitempty,max=5
	if s.Categories != nil && len(s.Categories) > 0 {
		if len(s.Categories) > 5 {
			return fmt.Errorf("field Categories must have at most 5 elements")
		}
	}
	// Numbers: min=1
	if len(s.Numbers) < 1 {
		return fmt.Errorf("field Numbers must have at least 1 elements")
	}
	return nil
}

func (s *SliceOfPointers) Validate() error {
	// Items: required,min=1
	if s.Items == nil || len(s.Items) == 0 {
		return fmt.Errorf("field Items is required")
	}
	if len(s.Items) < 1 {
		return fmt.Errorf("field Items must have at least 1 elements")
	}
	return nil
}
