// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package iso4217

import (
	"fmt"
)

func (p *Payment) Validate() error {
	// Currency: required,iso4217
	if p.Currency == "" {
		return fmt.Errorf("field Currency is required")
	}
	iso4217Codes1 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes1[p.Currency]; !ok {
		return fmt.Errorf("field Currency must be a valid ISO 4217 currency code")
	}
	// BaseCurrency: iso4217
	iso4217Codes2 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes2[p.BaseCurrency]; !ok {
		return fmt.Errorf("field BaseCurrency must be a valid ISO 4217 currency code")
	}
	// TargetCurrency: omitempty,iso4217
	if p.TargetCurrency != nil {
		iso4217Codes3 := map[string]struct{}{
			"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
			"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
			"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
			"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
			"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
			"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
			"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
			"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
			"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
			"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
			"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
			"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
			"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
			"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
			"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
			"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
			"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
			"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
			"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
			"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
			"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
			"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
			"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
			"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
			"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
			"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
			"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
			"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
			"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
			"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
			"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
			"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
			"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
			"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
			"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
			"XPD": {}, "XPT": {}, "XAG": {},
		}
		if _, ok := iso4217Codes3[*p.TargetCurrency]; !ok {
			return fmt.Errorf("field TargetCurrency must be a valid ISO 4217 currency code")
		}
	}
	// Amount: required,gt=0
	if p.Amount == 0 {
		return fmt.Errorf("field Amount is required")
	}
	if p.Amount <= 0 {
		return fmt.Errorf("field Amount must be greater than 0")
	}
	return nil
}

func (m *MultiCurrencyTransaction) Validate() error {
	// FromCurrency: required,iso4217
	if m.FromCurrency == "" {
		return fmt.Errorf("field FromCurrency is required")
	}
	iso4217Codes4 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes4[m.FromCurrency]; !ok {
		return fmt.Errorf("field FromCurrency must be a valid ISO 4217 currency code")
	}
	// ToCurrency: required,iso4217
	if m.ToCurrency == "" {
		return fmt.Errorf("field ToCurrency is required")
	}
	iso4217Codes5 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes5[m.ToCurrency]; !ok {
		return fmt.Errorf("field ToCurrency must be a valid ISO 4217 currency code")
	}
	// FeeCurrency: iso4217
	iso4217Codes6 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes6[m.FeeCurrency]; !ok {
		return fmt.Errorf("field FeeCurrency must be a valid ISO 4217 currency code")
	}
	return nil
}
