// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package iso3166_alpha2

import (
	"fmt"
)

func (a *Address) Validate() error {
	// Country: iso3166_1_alpha2
	iso3166_1_alpha2Codes1 := map[string]struct{}{
		"AF": {}, "AX": {}, "AL": {}, "DZ": {}, "AS": {},
		"AD": {}, "AO": {}, "AI": {}, "AQ": {}, "AG": {},
		"AR": {}, "AM": {}, "AW": {}, "AU": {}, "AT": {},
		"AZ": {}, "BS": {}, "BH": {}, "BD": {}, "BB": {},
		"BY": {}, "BE": {}, "BZ": {}, "BJ": {}, "BM": {},
		"BT": {}, "BO": {}, "BQ": {}, "BA": {}, "BW": {},
		"BV": {}, "BR": {}, "IO": {}, "BN": {}, "BG": {},
		"BF": {}, "BI": {}, "KH": {}, "CM": {}, "CA": {},
		"CV": {}, "KY": {}, "CF": {}, "TD": {}, "CL": {},
		"CN": {}, "CX": {}, "CC": {}, "CO": {}, "KM": {},
		"CG": {}, "CD": {}, "CK": {}, "CR": {}, "CI": {},
		"HR": {}, "CU": {}, "CW": {}, "CY": {}, "CZ": {},
		"DK": {}, "DJ": {}, "DM": {}, "DO": {}, "EC": {},
		"EG": {}, "SV": {}, "GQ": {}, "ER": {}, "EE": {},
		"ET": {}, "FK": {}, "FO": {}, "FJ": {}, "FI": {},
		"FR": {}, "GF": {}, "PF": {}, "TF": {}, "GA": {},
		"GM": {}, "GE": {}, "DE": {}, "GH": {}, "GI": {},
		"GR": {}, "GL": {}, "GD": {}, "GP": {}, "GU": {},
		"GT": {}, "GG": {}, "GN": {}, "GW": {}, "GY": {},
		"HT": {}, "HM": {}, "VA": {}, "HN": {}, "HK": {},
		"HU": {}, "IS": {}, "IN": {}, "ID": {}, "IR": {},
		"IQ": {}, "IE": {}, "IM": {}, "IL": {}, "IT": {},
		"JM": {}, "JP": {}, "JE": {}, "JO": {}, "KZ": {},
		"KE": {}, "KI": {}, "KP": {}, "KR": {}, "KW": {},
		"KG": {}, "LA": {}, "LV": {}, "LB": {}, "LS": {},
		"LR": {}, "LY": {}, "LI": {}, "LT": {}, "LU": {},
		"MO": {}, "MK": {}, "MG": {}, "MW": {}, "MY": {},
		"MV": {}, "ML": {}, "MT": {}, "MH": {}, "MQ": {},
		"MR": {}, "MU": {}, "YT": {}, "MX": {}, "FM": {},
		"MD": {}, "MC": {}, "MN": {}, "ME": {}, "MS": {},
		"MA": {}, "MZ": {}, "MM": {}, "NA": {}, "NR": {},
		"NP": {}, "NL": {}, "NC": {}, "NZ": {}, "NI": {},
		"NE": {}, "NG": {}, "NU": {}, "NF": {}, "MP": {},
		"NO": {}, "OM": {}, "PK": {}, "PW": {}, "PS": {},
		"PA": {}, "PG": {}, "PY": {}, "PE": {}, "PH": {},
		"PN": {}, "PL": {}, "PT": {}, "PR": {}, "QA": {},
		"RE": {}, "RO": {}, "RU": {}, "RW": {}, "BL": {},
		"SH": {}, "KN": {}, "LC": {}, "MF": {}, "PM": {},
		"VC": {}, "WS": {}, "SM": {}, "ST": {}, "SA": {},
		"SN": {}, "RS": {}, "SC": {}, "SL": {}, "SG": {},
		"SX": {}, "SK": {}, "SI": {}, "SB": {}, "SO": {},
		"ZA": {}, "GS": {}, "SS": {}, "ES": {}, "LK": {},
		"SD": {}, "SR": {}, "SJ": {}, "SZ": {}, "SE": {},
		"CH": {}, "SY": {}, "TW": {}, "TJ": {}, "TZ": {},
		"TH": {}, "TL": {}, "TG": {}, "TK": {}, "TO": {},
		"TT": {}, "TN": {}, "TR": {}, "TM": {}, "TC": {},
		"TV": {}, "UG": {}, "UA": {}, "AE": {}, "GB": {},
		"US": {}, "UM": {}, "UY": {}, "UZ": {}, "VU": {},
		"VE": {}, "VN": {}, "VG": {}, "VI": {}, "WF": {},
		"EH": {}, "YE": {}, "ZM": {}, "ZW": {}, "XK": {},
	}
	if _, ok := iso3166_1_alpha2Codes1[a.Country]; !ok {
		return fmt.Errorf("field Country must be a valid ISO 3166-1 alpha-2 country code")
	}
	// OptionalCountry: omitempty,iso3166_1_alpha2
	if a.OptionalCountry != nil {
		iso3166_1_alpha2Codes2 := map[string]struct{}{
			"AF": {}, "AX": {}, "AL": {}, "DZ": {}, "AS": {},
			"AD": {}, "AO": {}, "AI": {}, "AQ": {}, "AG": {},
			"AR": {}, "AM": {}, "AW": {}, "AU": {}, "AT": {},
			"AZ": {}, "BS": {}, "BH": {}, "BD": {}, "BB": {},
			"BY": {}, "BE": {}, "BZ": {}, "BJ": {}, "BM": {},
			"BT": {}, "BO": {}, "BQ": {}, "BA": {}, "BW": {},
			"BV": {}, "BR": {}, "IO": {}, "BN": {}, "BG": {},
			"BF": {}, "BI": {}, "KH": {}, "CM": {}, "CA": {},
			"CV": {}, "KY": {}, "CF": {}, "TD": {}, "CL": {},
			"CN": {}, "CX": {}, "CC": {}, "CO": {}, "KM": {},
			"CG": {}, "CD": {}, "CK": {}, "CR": {}, "CI": {},
			"HR": {}, "CU": {}, "CW": {}, "CY": {}, "CZ": {},
			"DK": {}, "DJ": {}, "DM": {}, "DO": {}, "EC": {},
			"EG": {}, "SV": {}, "GQ": {}, "ER": {}, "EE": {},
			"ET": {}, "FK": {}, "FO": {}, "FJ": {}, "FI": {},
			"FR": {}, "GF": {}, "PF": {}, "TF": {}, "GA": {},
			"GM": {}, "GE": {}, "DE": {}, "GH": {}, "GI": {},
			"GR": {}, "GL": {}, "GD": {}, "GP": {}, "GU": {},
			"GT": {}, "GG": {}, "GN": {}, "GW": {}, "GY": {},
			"HT": {}, "HM": {}, "VA": {}, "HN": {}, "HK": {},
			"HU": {}, "IS": {}, "IN": {}, "ID": {}, "IR": {},
			"IQ": {}, "IE": {}, "IM": {}, "IL": {}, "IT": {},
			"JM": {}, "JP": {}, "JE": {}, "JO": {}, "KZ": {},
			"KE": {}, "KI": {}, "KP": {}, "KR": {}, "KW": {},
			"KG": {}, "LA": {}, "LV": {}, "LB": {}, "LS": {},
			"LR": {}, "LY": {}, "LI": {}, "LT": {}, "LU": {},
			"MO": {}, "MK": {}, "MG": {}, "MW": {}, "MY": {},
			"MV": {}, "ML": {}, "MT": {}, "MH": {}, "MQ": {},
			"MR": {}, "MU": {}, "YT": {}, "MX": {}, "FM": {},
			"MD": {}, "MC": {}, "MN": {}, "ME": {}, "MS": {},
			"MA": {}, "MZ": {}, "MM": {}, "NA": {}, "NR": {},
			"NP": {}, "NL": {}, "NC": {}, "NZ": {}, "NI": {},
			"NE": {}, "NG": {}, "NU": {}, "NF": {}, "MP": {},
			"NO": {}, "OM": {}, "PK": {}, "PW": {}, "PS": {},
			"PA": {}, "PG": {}, "PY": {}, "PE": {}, "PH": {},
			"PN": {}, "PL": {}, "PT": {}, "PR": {}, "QA": {},
			"RE": {}, "RO": {}, "RU": {}, "RW": {}, "BL": {},
			"SH": {}, "KN": {}, "LC": {}, "MF": {}, "PM": {},
			"VC": {}, "WS": {}, "SM": {}, "ST": {}, "SA": {},
			"SN": {}, "RS": {}, "SC": {}, "SL": {}, "SG": {},
			"SX": {}, "SK": {}, "SI": {}, "SB": {}, "SO": {},
			"ZA": {}, "GS": {}, "SS": {}, "ES": {}, "LK": {},
			"SD": {}, "SR": {}, "SJ": {}, "SZ": {}, "SE": {},
			"CH": {}, "SY": {}, "TW": {}, "TJ": {}, "TZ": {},
			"TH": {}, "TL": {}, "TG": {}, "TK": {}, "TO": {},
			"TT": {}, "TN": {}, "TR": {}, "TM": {}, "TC": {},
			"TV": {}, "UG": {}, "UA": {}, "AE": {}, "GB": {},
			"US": {}, "UM": {}, "UY": {}, "UZ": {}, "VU": {},
			"VE": {}, "VN": {}, "VG": {}, "VI": {}, "WF": {},
			"EH": {}, "YE": {}, "ZM": {}, "ZW": {}, "XK": {},
		}
		if _, ok := iso3166_1_alpha2Codes2[*a.OptionalCountry]; !ok {
			return fmt.Errorf("field OptionalCountry must be a valid ISO 3166-1 alpha-2 country code")
		}
	}
	return nil
}
