// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package email

import (
	"fmt"
	"regexp"
)

var pkg_emailRegexp_952c0aba = regexp.MustCompile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")

func (u *User) Validate() error {
	// Email: email
	if !pkg_emailRegexp_952c0aba.MatchString(u.Email) {
		return fmt.Errorf("field Email must be a valid email address")
	}
	// OptionalEmail: omitempty,email
	if u.OptionalEmail != nil {
		if !pkg_emailRegexp_952c0aba.MatchString(*u.OptionalEmail) {
			return fmt.Errorf("field OptionalEmail must be a valid email address")
		}
	}
	return nil
}

func (c *Contact) Validate() error {
	// Name: required
	if c.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	// EmailAddress: omitempty,email
	if c.EmailAddress != nil && len(c.EmailAddress) > 0 {
		for i, email := range c.EmailAddress {
			if !pkg_emailRegexp_952c0aba.MatchString(email) {
				return fmt.Errorf("field EmailAddress[%d] must be a valid email address", i)
			}
		}
	}
	// BackupEmails: omitempty,email
	if c.BackupEmails != nil && len(c.BackupEmails) > 0 {
		for i, email := range c.BackupEmails {
			if email == nil {
				continue
			}
			if !pkg_emailRegexp_952c0aba.MatchString(*email) {
				return fmt.Errorf("field BackupEmails[%d] must be a valid email address", i)
			}
		}
	}
	return nil
}

func (t *TestStruct) Validate() error {
	// EmailsNoDive: omitempty,email
	if t.EmailsNoDive != nil && len(t.EmailsNoDive) > 0 {
		for i, email := range t.EmailsNoDive {
			if !pkg_emailRegexp_952c0aba.MatchString(email) {
				return fmt.Errorf("field EmailsNoDive[%d] must be a valid email address", i)
			}
		}
	}
	return nil
}
