// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package required_without

import (
	"fmt"
)

func (f *FixedPenalty) Validate() error {
	// Amount: required,gt=0
	if f.Amount == 0 {
		return fmt.Errorf("field Amount is required")
	}
	if f.Amount <= 0 {
		return fmt.Errorf("field Amount must be greater than 0")
	}
	// Currency: required,iso4217
	if f.Currency == "" {
		return fmt.Errorf("field Currency is required")
	}
	iso4217Codes1 := map[string]struct{}{
		"AFN": {}, "EUR": {}, "ALL": {}, "DZD": {}, "USD": {},
		"AOA": {}, "XCD": {}, "ARS": {}, "AMD": {}, "AWG": {},
		"AUD": {}, "AZN": {}, "BSD": {}, "BHD": {}, "BDT": {},
		"BBD": {}, "BYN": {}, "BZD": {}, "XOF": {}, "BMD": {},
		"INR": {}, "BTN": {}, "BOB": {}, "BOV": {}, "BAM": {},
		"BWP": {}, "NOK": {}, "BRL": {}, "BND": {}, "BGN": {},
		"BIF": {}, "CVE": {}, "KHR": {}, "XAF": {}, "CAD": {},
		"KYD": {}, "CLP": {}, "CLF": {}, "CNY": {}, "COP": {},
		"COU": {}, "KMF": {}, "CDF": {}, "NZD": {}, "CRC": {},
		"CUP": {}, "CZK": {}, "DKK": {}, "DJF": {}, "DOP": {},
		"EGP": {}, "SVC": {}, "ERN": {}, "SZL": {}, "ETB": {},
		"FKP": {}, "FJD": {}, "XPF": {}, "GMD": {}, "GEL": {},
		"GHS": {}, "GIP": {}, "GTQ": {}, "GBP": {}, "GNF": {},
		"GYD": {}, "HTG": {}, "HNL": {}, "HKD": {}, "HUF": {},
		"ISK": {}, "IDR": {}, "XDR": {}, "IRR": {}, "IQD": {},
		"ILS": {}, "JMD": {}, "JPY": {}, "JOD": {}, "KZT": {},
		"KES": {}, "KPW": {}, "KRW": {}, "KWD": {}, "KGS": {},
		"LAK": {}, "LBP": {}, "LSL": {}, "ZAR": {}, "LRD": {},
		"LYD": {}, "CHF": {}, "MOP": {}, "MKD": {}, "MGA": {},
		"MWK": {}, "MYR": {}, "MVR": {}, "MRU": {}, "MUR": {},
		"XUA": {}, "MXN": {}, "MXV": {}, "MDL": {}, "MNT": {},
		"MAD": {}, "MZN": {}, "MMK": {}, "NAD": {}, "NPR": {},
		"NIO": {}, "NGN": {}, "OMR": {}, "PKR": {}, "PAB": {},
		"PGK": {}, "PYG": {}, "PEN": {}, "PHP": {}, "PLN": {},
		"QAR": {}, "RON": {}, "RUB": {}, "RWF": {}, "SHP": {},
		"WST": {}, "STN": {}, "SAR": {}, "RSD": {}, "SCR": {},
		"SLE": {}, "SGD": {}, "XSU": {}, "SBD": {}, "SOS": {},
		"SSP": {}, "LKR": {}, "SDG": {}, "SRD": {}, "SEK": {},
		"CHE": {}, "CHW": {}, "SYP": {}, "TWD": {}, "TJS": {},
		"TZS": {}, "THB": {}, "TOP": {}, "TTD": {}, "TND": {},
		"TRY": {}, "TMT": {}, "UGX": {}, "UAH": {}, "AED": {},
		"USN": {}, "UYU": {}, "UYI": {}, "UYW": {}, "UZS": {},
		"VUV": {}, "VES": {}, "VED": {}, "VND": {}, "YER": {},
		"ZMW": {}, "ZWG": {}, "XBA": {}, "XBB": {}, "XBC": {},
		"XBD": {}, "XCG": {}, "XTS": {}, "XXX": {}, "XAU": {},
		"XPD": {}, "XPT": {}, "XAG": {},
	}
	if _, ok := iso4217Codes1[f.Currency]; !ok {
		return fmt.Errorf("field Currency must be a valid ISO 4217 currency code")
	}
	return nil
}

func (p *PercentagePenalty) Validate() error {
	// Percentage: required,gt=0,lte=100
	if p.Percentage == 0 {
		return fmt.Errorf("field Percentage is required")
	}
	if p.Percentage <= 0 {
		return fmt.Errorf("field Percentage must be greater than 0")
	}
	if p.Percentage > 100 {
		return fmt.Errorf("field Percentage must be at most 100")
	}
	return nil
}

func (p *Penalty) Validate() error {
	// FixedPenalty: required_without=PercentagePenalty
	if p.PercentagePenalty == nil && p.FixedPenalty == nil {
		return fmt.Errorf("field FixedPenalty is required when PercentagePenalty is not provided")
	}
	// PercentagePenalty: required_without=FixedPenalty
	if p.FixedPenalty == nil && p.PercentagePenalty == nil {
		return fmt.Errorf("field PercentagePenalty is required when FixedPenalty is not provided")
	}
	return nil
}

func (p *Payment) Validate() error {
	// CreditCard: required_without=BankAccount
	if p.BankAccount == nil && p.CreditCard == nil {
		return fmt.Errorf("field CreditCard is required when BankAccount is not provided")
	}
	// BankAccount: required_without=CreditCard
	if p.CreditCard == nil && p.BankAccount == nil {
		return fmt.Errorf("field BankAccount is required when CreditCard is not provided")
	}
	// Amount: required,gt=0
	if p.Amount == 0 {
		return fmt.Errorf("field Amount is required")
	}
	if p.Amount <= 0 {
		return fmt.Errorf("field Amount must be greater than 0")
	}
	return nil
}
