// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package dive_empty

import (
	"fmt"
)

func (c *CabinComponent) Validate() error {
	return nil
}

func (s *SeatColumn) Validate() error {
	return nil
}

func (s *SeatRow) Validate() error {
	return nil
}

func (c *CabinCompartment) Validate() error {
	// CabinComponent: omitempty,dive
	if c.CabinComponent != nil && len(c.CabinComponent) > 0 {
		for i := range c.CabinComponent {
			if err := c.CabinComponent[i].Validate(); err != nil {
				return fmt.Errorf("field CabinComponent[%d] validation failed: %w", i, err)
			}
		}
	}
	// SeatColumns: required,dive
	if c.SeatColumns == nil || len(c.SeatColumns) == 0 {
		return fmt.Errorf("field SeatColumns is required")
	}
	for i := range c.SeatColumns {
		if err := c.SeatColumns[i].Validate(); err != nil {
			return fmt.Errorf("field SeatColumns[%d] validation failed: %w", i, err)
		}
	}
	// SeatRows: required,dive
	if c.SeatRows == nil || len(c.SeatRows) == 0 {
		return fmt.Errorf("field SeatRows is required")
	}
	for i := range c.SeatRows {
		if err := c.SeatRows[i].Validate(); err != nil {
			return fmt.Errorf("field SeatRows[%d] validation failed: %w", i, err)
		}
	}
	return nil
}
