// Code generated by validgen. DO NOT EDIT.

package datetime

import (
	"fmt"
	"time"
)

func (e *Event) Validate() error {
	// Name: required
	if e.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	// StartTime: required,datetime=2006-01-02T15:04:05Z07:00
	if e.StartTime == "" {
		return fmt.Errorf("field StartTime is required")
	}
	if _, err := time.Parse("2006-01-02T15:04:05Z07:00", e.StartTime); err != nil {
		return fmt.Errorf("field StartTime must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
	}
	// EndTime: datetime=2006-01-02T15:04:05Z07:00
	if _, err := time.Parse("2006-01-02T15:04:05Z07:00", e.EndTime); err != nil {
		return fmt.Errorf("field EndTime must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
	}
	// CreatedAt: datetime=2006-01-02
	if _, err := time.Parse("2006-01-02", e.CreatedAt); err != nil {
		return fmt.Errorf("field CreatedAt must be a valid datetime in format 2006-01-02: %w", err)
	}
	// UpdatedAt: omitempty,datetime=2006-01-02T15:04:05Z07:00
	if e.UpdatedAt != nil {
		if _, err := time.Parse("2006-01-02T15:04:05Z07:00", *e.UpdatedAt); err != nil {
			return fmt.Errorf("field UpdatedAt must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
		}
	}
	return nil
}

func (d *DateFormats) Validate() error {
	// RFC3339: datetime=2006-01-02T15:04:05Z07:00
	if _, err := time.Parse("2006-01-02T15:04:05Z07:00", d.RFC3339); err != nil {
		return fmt.Errorf("field RFC3339 must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
	}
	// DateOnly: datetime=2006-01-02
	if _, err := time.Parse("2006-01-02", d.DateOnly); err != nil {
		return fmt.Errorf("field DateOnly must be a valid datetime in format 2006-01-02: %w", err)
	}
	// TimeOnly: datetime=15:04:05
	if _, err := time.Parse("15:04:05", d.TimeOnly); err != nil {
		return fmt.Errorf("field TimeOnly must be a valid datetime in format 15:04:05: %w", err)
	}
	// CustomDate: datetime=01/02/2006
	if _, err := time.Parse("01/02/2006", d.CustomDate); err != nil {
		return fmt.Errorf("field CustomDate must be a valid datetime in format 01/02/2006: %w", err)
	}
	// UnixDate: datetime=Mon Jan _2 15:04:05 MST 2006
	if _, err := time.Parse("Mon Jan _2 15:04:05 MST 2006", d.UnixDate); err != nil {
		return fmt.Errorf("field UnixDate must be a valid datetime in format Mon Jan _2 15:04:05 MST 2006: %w", err)
	}
	return nil
}

func (c *CustomStringTypes) Validate() error {
	// Timestamp: datetime=2006-01-02T15:04:05Z07:00
	if _, err := time.Parse("2006-01-02T15:04:05Z07:00", string(c.Timestamp)); err != nil {
		return fmt.Errorf("field Timestamp must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
	}
	// Date: datetime=2006-01-02
	if _, err := time.Parse("2006-01-02", string(c.Date)); err != nil {
		return fmt.Errorf("field Date must be a valid datetime in format 2006-01-02: %w", err)
	}
	// OptionalTs: omitempty,datetime=2006-01-02T15:04:05Z07:00
	if c.OptionalTs != nil {
		if _, err := time.Parse("2006-01-02T15:04:05Z07:00", string(*c.OptionalTs)); err != nil {
			return fmt.Errorf("field OptionalTs must be a valid datetime in format 2006-01-02T15:04:05Z07:00: %w", err)
		}
	}
	return nil
}
