// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package dive

import (
	"fmt"
)

func (a *Address) Validate() error {
	// Street: required
	if a.Street == "" {
		return fmt.Errorf("field Street is required")
	}
	// City: required
	if a.City == "" {
		return fmt.Errorf("field City is required")
	}
	// ZipCode: required,min=5,max=10
	if a.ZipCode == "" {
		return fmt.Errorf("field ZipCode is required")
	}
	if len(a.ZipCode) < 5 {
		return fmt.Errorf("field ZipCode must be at least 5 characters")
	}
	if len(a.ZipCode) > 10 {
		return fmt.Errorf("field ZipCode must be at most 10 characters")
	}
	return nil
}

func (c *Contact) Validate() error {
	// Email: required
	if c.Email == "" {
		return fmt.Errorf("field Email is required")
	}
	// Phone: omitempty,min=10
	if c.Phone != "" {
		if len(c.Phone) < 10 {
			return fmt.Errorf("field Phone must be at least 10 characters")
		}
	}
	return nil
}

func (p *Person) Validate() error {
	// Name: required
	if p.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	// Address: required,dive
	if p.Address == nil {
		return fmt.Errorf("field Address is required")
	}
	if p.Address != nil {
		if err := p.Address.Validate(); err != nil {
			return fmt.Errorf("field Address validation failed: %w", err)
		}
	}
	// Contact: dive
	if err := p.Contact.Validate(); err != nil {
		return fmt.Errorf("field Contact validation failed: %w", err)
	}
	return nil
}

func (i *Item) Validate() error {
	// Name: required
	if i.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	// Quantity: min=1
	if i.Quantity < 1 {
		return fmt.Errorf("field Quantity must be at least 1")
	}
	// Price: gt=0
	if i.Price <= 0 {
		return fmt.Errorf("field Price must be greater than 0")
	}
	return nil
}

func (o *Order) Validate() error {
	// ID: required
	if o.ID == "" {
		return fmt.Errorf("field ID is required")
	}
	// Items: required,min=1,dive
	if o.Items == nil || len(o.Items) == 0 {
		return fmt.Errorf("field Items is required")
	}
	if len(o.Items) < 1 {
		return fmt.Errorf("field Items must have at least 1 elements")
	}
	for i := range o.Items {
		if err := o.Items[i].Validate(); err != nil {
			return fmt.Errorf("field Items[%d] validation failed: %w", i, err)
		}
	}
	return nil
}

func (c *Company) Validate() error {
	// Name: required
	if c.Name == "" {
		return fmt.Errorf("field Name is required")
	}
	// Employees: min=1,dive
	if len(c.Employees) < 1 {
		return fmt.Errorf("field Employees must have at least 1 elements")
	}
	for i := range c.Employees {
		if err := c.Employees[i].Validate(); err != nil {
			return fmt.Errorf("field Employees[%d] validation failed: %w", i, err)
		}
	}
	// HQ: required,dive
	if c.HQ == nil {
		return fmt.Errorf("field HQ is required")
	}
	if c.HQ != nil {
		if err := c.HQ.Validate(); err != nil {
			return fmt.Errorf("field HQ validation failed: %w", err)
		}
	}
	return nil
}
