// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package main

import (
	"fmt"
	"regexp"
)

var types_emailRegexp_952c0aba = regexp.MustCompile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")

func (u *UserRegistration) Validate() error {
	// Username: required,min=3,max=20
	if u.Username == "" {
		return fmt.Errorf("field Username is required")
	}
	if len(u.Username) < 3 {
		return fmt.Errorf("field Username must be at least 3 characters")
	}
	if len(u.Username) > 20 {
		return fmt.Errorf("field Username must be at most 20 characters")
	}
	// Email: required,email
	if u.Email == "" {
		return fmt.Errorf("field Email is required")
	}
	if !types_emailRegexp_952c0aba.MatchString(u.Email) {
		return fmt.Errorf("field Email must be a valid email address")
	}
	// Password: required,min=8
	if u.Password == "" {
		return fmt.Errorf("field Password is required")
	}
	if len(u.Password) < 8 {
		return fmt.Errorf("field Password must be at least 8 characters")
	}
	// ConfirmPassword: required,eqfield=Password
	if u.ConfirmPassword == "" {
		return fmt.Errorf("field ConfirmPassword is required")
	}
	if u.ConfirmPassword != u.Password {
		return fmt.Errorf("field ConfirmPassword must equal field Password")
	}
	return nil
}

func (o *OrderModificationRequest) Validate() error {
	// CancelOrderId: omitempty,eqfield=OrderId
	if o.CancelOrderId != nil {
		if o.CancelOrderId != nil {
			if *o.CancelOrderId != o.OrderId {
				return fmt.Errorf("field CancelOrderId must equal field OrderId")
			}
		} else {
			return fmt.Errorf("field CancelOrderId must equal field OrderId (pointer is nil)")
		}
	}
	// OrderId: required
	if o.OrderId == "" {
		return fmt.Errorf("field OrderId is required")
	}
	return nil
}
