// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package pointers

import (
	"fmt"
)

func (p *PointerFields) Validate() error {
	// Name: required
	if p.Name == nil {
		return fmt.Errorf("field Name is required")
	}
	// Age: omitempty,gt=0,lt=120
	if p.Age != nil {
		if *p.Age <= 0 {
			return fmt.Errorf("field Age must be greater than 0")
		}
		if *p.Age >= 120 {
			return fmt.Errorf("field Age must be less than 120")
		}
	}
	return nil
}

func (m *MixedPointers) Validate() error {
	// ID: required
	if m.ID == "" {
		return fmt.Errorf("field ID is required")
	}
	// Optional: omitempty,min=5
	if m.Optional != nil {
		if len(*m.Optional) < 5 {
			return fmt.Errorf("field Optional must be at least 5 characters")
		}
	}
	// Count: omitempty,gte=1
	if m.Count != nil {
		if *m.Count < 1 {
			return fmt.Errorf("field Count must be at least 1")
		}
	}
	return nil
}
