// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package demo

import (
	"fmt"
)

func (u *User) Validate() error {
	// ID: required
	if u.ID == "" {
		return fmt.Errorf("field ID is required")
	}
	// Username: required,min=3,max=20
	if u.Username == "" {
		return fmt.Errorf("field Username is required")
	}
	if len(u.Username) < 3 {
		return fmt.Errorf("field Username must be at least 3 characters")
	}
	if len(u.Username) > 20 {
		return fmt.Errorf("field Username must be at most 20 characters")
	}
	// Email: required
	if u.Email == "" {
		return fmt.Errorf("field Email is required")
	}
	// Age: gte=18,lte=100
	if u.Age < 18 {
		return fmt.Errorf("field Age must be at least 18")
	}
	if u.Age > 100 {
		return fmt.Errorf("field Age must be at most 100")
	}
	// Tags: min=1,max=5,unique
	if len(u.Tags) < 1 {
		return fmt.Errorf("field Tags must have at least 1 elements")
	}
	if len(u.Tags) > 5 {
		return fmt.Errorf("field Tags must have at most 5 elements")
	}
	seenTags := make(map[string]bool, len(u.Tags))
	for i, item := range u.Tags {
		if seenTags[item] {
			return fmt.Errorf("field Tags has duplicate value at index %d", i)
		}
		seenTags[item] = true
	}
	// Profile: required,dive
	if u.Profile == nil {
		return fmt.Errorf("field Profile is required")
	}
	if u.Profile != nil {
		if err := u.Profile.Validate(); err != nil {
			return fmt.Errorf("field Profile validation failed: %w", err)
		}
	}
	return nil
}

func (p *Profile) Validate() error {
	// Bio: required,max=500
	if p.Bio == "" {
		return fmt.Errorf("field Bio is required")
	}
	if len(p.Bio) > 500 {
		return fmt.Errorf("field Bio must be at most 500 characters")
	}
	// Website: omitempty,min=10
	if p.Website != "" {
		if len(p.Website) < 10 {
			return fmt.Errorf("field Website must be at least 10 characters")
		}
	}
	return nil
}
