// Code generated by validgen. DO NOT EDIT.

package complex

import (
	"fmt"
)

func (c *ComplexValidation) Validate() error {
	// Username: required,min=3,max=20
	if c.Username == "" {
		return fmt.Errorf("field Username is required")
	}
	if len(c.Username) < 3 {
		return fmt.Errorf("field Username must be at least 3 characters")
	}
	if len(c.Username) > 20 {
		return fmt.Errorf("field Username must be at most 20 characters")
	}
	// Age: omitempty,gte=18,lte=100
	if c.Age != nil {
		if *c.Age < 18 {
			return fmt.Errorf("field Age must be at least 18")
		}
		if *c.Age > 100 {
			return fmt.Errorf("field Age must be at most 100")
		}
	}
	// Tags: required,min=1,max=10,unique
	if c.Tags == nil || len(c.Tags) == 0 {
		return fmt.Errorf("field Tags is required")
	}
	if len(c.Tags) < 1 {
		return fmt.Errorf("field Tags must have at least 1 elements")
	}
	if len(c.Tags) > 10 {
		return fmt.Errorf("field Tags must have at most 10 elements")
	}
	seenTags := make(map[string]bool, len(c.Tags))
	for i, item := range c.Tags {
		if seenTags[item] {
			return fmt.Errorf("field Tags has duplicate value at index %d", i)
		}
		seenTags[item] = true
	}
	// Profile: required,dive
	if c.Profile == nil {
		return fmt.Errorf("field Profile is required")
	}
	if c.Profile != nil {
		if err := c.Profile.Validate(); err != nil {
			return fmt.Errorf("field Profile validation failed: %w", err)
		}
	}
	// Items: min=1,dive,unique=Code
	if len(c.Items) < 1 {
		return fmt.Errorf("field Items must have at least 1 elements")
	}
	for i := range c.Items {
		if err := c.Items[i].Validate(); err != nil {
			return fmt.Errorf("field Items[%d] validation failed: %w", i, err)
		}
	}
	seenItemsCode := make(map[string]bool, len(c.Items))
	for i, item := range c.Items {
		if seenItemsCode[item.Code] {
			return fmt.Errorf("field Items has duplicate Code at index %d", i)
		}
		seenItemsCode[item.Code] = true
	}
	return nil
}

func (p *Profile) Validate() error {
	// Bio: required,max=500
	if p.Bio == "" {
		return fmt.Errorf("field Bio is required")
	}
	if len(p.Bio) > 500 {
		return fmt.Errorf("field Bio must be at most 500 characters")
	}
	// Website: omitempty,min=10
	if p.Website != "" {
		if len(p.Website) < 10 {
			return fmt.Errorf("field Website must be at least 10 characters")
		}
	}
	return nil
}

func (i *Item) Validate() error {
	// Description: required
	if i.Description == "" {
		return fmt.Errorf("field Description is required")
	}
	// Price: gt=0
	if i.Price <= 0 {
		return fmt.Errorf("field Price must be greater than 0")
	}
	return nil
}
