// THIS IS AUTOGENERATED FILES, DO NOT EDIT IT

package models

import (
	"fmt"
)

func (e *Error) Validate() error {
	// LangCode: required
	if e.LangCode == "" {
		return fmt.Errorf("field LangCode is required")
	}
	// TypeCode: required
	if e.TypeCode == "" {
		return fmt.Errorf("field TypeCode is required")
	}
	return nil
}
